### ISSUE TITLE
New Datatypes

### ISSUE THREAD

**Issue by Alastairsc** [lilfolr/CITS4406-Assignment2#11]
For the new data types (date, time day of the week, hyperlink) still need to include the statistics in the generated report, implement analysis for these types, test data detection and error detection for these types.

**Comment by KieranER** [comment]
Stats in report done, basic analysis implemented, still need to add test files and double check reporting of detected errors.

**Comment by lilfolr** [comment]
Let me know when you've made test files so i can check the charts work

**Comment by Alastairsc** [comment]
Stats available, charts work, no known problems, closing
