### ISSUE TITLE
Email csv not working

### ISSUE THREAD

**Issue by JJHedges** [lilfolr/CITS4406-Assignment2#14]
Email csv currently isn't working, saying there is nothing in the raw_data (list index out of range at 0) the problem appears to be coming from line 495-501 in data where no raw_data is added unless the amount of columns is 1?

**Comment by JanV123** [comment]
my fault. should now work.

**Comment by JJHedges** [comment]
Did you push the changes? Not seeing them yet

**Comment by JanV123** [comment]
Did you see it now? It should now work. Can someone else confirm.

**Comment by lilfolr** [comment]
Error has been fixed
