### ISSUE TITLE
Currency problem

### ISSUE THREAD

**Issue by Alastairsc** [lilfolr/CITS4406-Assignment2#15]
They way excel handles large currency numbers is that it puts commas every 1000, ie 10 000 becomes 10,000. This messes with the program as it is recorded as "$10,000 " and becomes (10,0). This comes up as an error on line 126 of analyser.py. example of this is in test A. Need to somehow convert the intepreted comma as *1000 or something and convert to a number

**Comment by JJHedges** [comment]
Fixed.
