### ISSUE TITLE
Dates recognized as String types

### ISSUE THREAD

**Issue by JanV123** [lilfolr/CITS4406-Assignment2#16]
Dates are analysed as String types.

**Comment by Alastairm** [comment]
Have you tested this with Test B.csv?
 I'm still getting dates detected as strings (Test Date (column 11) & End Date (column 22)).

**Comment by KieranER** [comment]
That is because those dates don't match the 2 formats we're currently accounting for, i.e. dd/mm/yyyy, and dd/mm/yy.

There's a practically infinite number of ways of writing dates, and if you write a regex that fully accounts for them, it's simply \w

**Comment by Alastairsc** [comment]
thats acceptable, we will have to just put in the documentations that we only support date analysis if they are given in those formats we support

**Comment by lilfolr** [comment]
If we have time it may not be a bad idea to support the formats excel does by default
![image](https://cloud.githubusercontent.com/assets/9531064/10420778/c59200f0-70cd-11e5-81f3-41666b552a9f.png)

**Comment by Alastairsc** [comment]
thats funny, by default my version of excel only uses dashes. Thats why test B has mosty dashes. It would be good to support at least dd-mm-yy and dd-mm-yyyy. It shouldnt be too hard to add to ur regex, just make it accept '\' or '-'

**Comment by KieranER** [comment]
Mmm the variations on /-\ is easy enough, the main problem would be swapping to mm/dd/yyyy or anything involving text months

**Comment by lilfolr** [comment]
Don't do mm/dd. That would cause issues like: is "1/2" 1 Feb or 2 Jan.
