### ISSUE TITLE
MaskError Exception in data.analysis() 

### ISSUE THREAD

**Issue by Alastairm** [lilfolr/CITS4406-Assignment2#19]
I get a MaskError Exception during analysis on Test A Errors.csv with no template. It sounds like it's to do with trying to analyse data with invalid values ( probably "inf" from the scientific notation column). Stack trace below.

data.py in analysis
                 column.analysis = self.analysers[column.type](column.values, self.std_devs_val)  
analyser.py in __init__
               self.pval = mstats.normaltest(array(values))[1] 
.local/lib/python3.4/site-packages/scipy/stats/mstats_basic.py in normaltest
               k, _ = kurtosistest(a, axis) 
.local/lib/python3.4/site-packages/scipy/stats/mstats_basic.py in kurtosistest
              denom[denom < 0] = masked 
.local/lib/python3.4/site-packages/numpy/ma/core.py in __setitem__
               raise MaskError('Cannot alter the masked element.')

**Comment by Alastairm** [comment]
It appears the value 5e65622 (cell P8) is converted to inf.
 Also 5.2e-65455 (cell P18) is converted to 0.0.

**Comment by JJHedges** [comment]
Yeah i'm not sure what to do with this one: https://github.com/lilfolr/CITS4406-Assignment2/issues/18

Rounding to infinity is pretty valid for 5x10^(65622) and rounding 5.2x10^(65455) is pretty valid as well. Not sure if it is possible to at the analysis point to change a value or remove it from analysis either.

**Comment by JJHedges** [comment]
Apparently the maximum allowed number for floats is 1.7976931348623157e+308 and -308 for negative. I guess I could add the value to errors if it is outside this but for the standalone program this would mean it would crash anyway?

**Comment by Alastairm** [comment]
haha yeap going to 0 is fine, really didn't think about that one.
As for infinity, maybe columns with infinity should be skipped in analysis? because you can't really get meaningful statistics on sets containing infinity.

**Comment by Alastairsc** [comment]
those should be errors, or at least outliers, dont worry about processing them

**Comment by JJHedges** [comment]
I may have solved this, probably more testing needed. It appears that numpy is having an overflow issue with too positive / too negative numbers so I determined a number experimentally that it errored for and added this to list of errors and updated the cell to being blank and it seems to work now.

**Comment by JJHedges** [comment]
No one has complained yet so im closing this
