### ISSUE TITLE
0 not matched in integer regex

### ISSUE THREAD

**Issue by Alastairm** [lilfolr/CITS4406-Assignment2#22]
Not sure if it was something the client requested (if so just close this),
but 0 isn't currently considered an integer.
Neither are numbers beginning with +/-

**Comment by Alastairsc** [comment]
yeah the regex specifically doesnt recognise 0, i made it accept them manually, obviously i didnt do it properly if your still having problems, not sure about that +/- thing though

**Comment by Alastairm** [comment]
Fixed. I removed the [1-9] in  ^\s_[1-9]\d_ which only recognised numbers starting with 1-9
