### ISSUE TITLE
is column.analysis used anymore?

### ISSUE THREAD

**Issue by Alastairm** [lilfolr/CITS4406-Assignment2#26]
when choosing what analysis to perform column.type is used rather than column.analysis, and my understanding was they were identical? can we remove the column.analysis variable?

**Comment by JJHedges** [comment]
column.analysis holds the results of the analysis and is used later in report.py i.e. line 145

**Comment by Alastairm** [comment]
ahhhh that's a bit different to how I was using it on the datatypes page,
thanks for clarifying
