### ISSUE TITLE
Excel spreadsheets for linux

### ISSUE THREAD

**Issue by JJHedges** [lilfolr/CITS4406-Assignment2#3]
Excel spreadsheets don't seem to work for linux, it seems to be because of the slashes for filepaths being the wrong way, not sure how to fix

**Comment by JanV123** [comment]
.xls files or even .csv?

**Comment by JJHedges** [comment]
I tried it with the .xslx file, csv's are fine i think

**Comment by JanV123** [comment]
ok will try and check it out over the weekend

**Comment by Alastairsc** [comment]
actaully i didnt think about it, yeah it probaly wouldnt work with linux as i was basing my code on windows format, someone will probaly have to generalise it by splitting up by backslash and forward slash

**Comment by Alastairm** [comment]
To make path concatenation platform independent use os.path.join() (with no slashes in the arguments) rather than normal string concatenation.

**Comment by JJHedges** [comment]
Done, working on windows/linux
