### ISSUE TITLE
Extra template functionality

### ISSUE THREAD

**Issue by Alastairsc** [lilfolr/CITS4406-Assignment2#6]
Template should allow users to ignore specific errors if they dont care, eg floats in integer column, <1 etc

**Comment by Alastairsc** [comment]
allow users to ignore empty cells in non-empty rows, already does if users want to do this for all cells but it should be able to do it for only specific columns

**Comment by Alastairsc** [comment]
allow user to provide upper and lower bounds in template. eg for lat and longitude max would be 180, min would be -180. Everything else should be excluded and reported as an error

**Comment by JJHedges** [comment]
Done.
