### ISSUE TITLE
Space Delimited

### ISSUE THREAD

**Issue by Alastairsc** [lilfolr/CITS4406-Assignment2#7]
Does not work with space delimited files, not a big issue. But it is to do with the csv reader we are using, would have to use someother reader.

**Comment by Alastairsc** [comment]
Probaly have to use split instead of the reader

**Comment by JanV123** [comment]
been looking to get space delimiters working as well. Having posted at stack exchange, it seems this is a limitation of the sniffer. Some have suggested using split instead as you mentioned.

**Comment by JanV123** [comment]
I actually did make one using split before i had changed it to the sniffer. Maybe you can check if this is what you wanted:

re_separation = re.compile('[\s,;]+')
f = csv.reader(open(csv_file))
        #for row in f:
        for line in f:
            n_col = len(line)
            #print(n_col)
            if n_col == 1:
                result = re.split(re_separation, line[0])
                self.raw_data.append(result)
                #print(self.raw_data)
            else:
                self.raw_data.append(line)
                #print(self.raw_data)

**Comment by JanV123** [comment]
This should now work. Can someone else also confirm?

**Comment by JanV123** [comment]
templates for delimiters should now work

**Comment by Alastairsc** [comment]
Can confirm, works with template
