### ISSUE TITLE
Whole numbers in column of floats considered errors

### ISSUE THREAD

**Issue by Alastairm** [lilfolr/CITS4406-Assignment2#8]
in Column 40, Row 10 of Oil_original the value 99 is considered an error, but is clearly valid when you consider the rest of the column:
{105.3, 102.2, 113.6, 110.3, 111.4, 113.4, 99, 105.3, 102.2, 113.6, 110.3, 111.4, 113.4, 99.1 }
i.e. lack of a decimal point shouldn't necessarily be an error

**Comment by JJHedges** [comment]
We decided to just count them as errors to make error detection easier, unlikely that user has on purpose done float numbers >90% of the time without meaning for the entire column to be floats
